### ISSUE TITLE
Script tags in *.astro files breaks color scheme

### ISSUE THREAD

**Issue by adamjohnson** [Destiner/sublime-astro#1]
## How to reproduce

Insert any script tag into any `*.astro` template:

```html
<p>Some HTML</p>
<script>
  console.log('Hello there.');
</script>
<p>Some other HTML</p>
```

## Screenshots:

These are from `BaseLayout.astro` and `Tour.astro`.

![Astro BaseLayout file](https://user-images.githubusercontent.com/575865/146696342-51939298-27e8-4740-90ed-1961edecc7bd.png)

![Astro Tour Component](https://user-images.githubusercontent.com/575865/146696343-e4e2c29c-3204-4e71-9a9f-1e154b80608d.png)

I'm using ST v4 Stable Channel, build 4121 with the Material Theme Darker theme/color scheme.

Thanks for creating this package!

**Comment by Destiner** [comment]
Hey @adamjohnson.

Thanks for feedback! I'm not sure what causes this issue, but I know there were some fixes in VSCode highlighting package. I hope that backporting those fixes to ST will solve it.

**Comment by Destiner** [comment]
Alright, should be fixed in 1.2.0 (as well as those annoying quirks with CSS units)

**Comment by adamjohnson** [comment]
Much improved, 👏  🍻 ! Thanks for working on this.

I am still seeing some minor highlighting issues. _Way_ less of a big deal than before, but, perhaps still relevant. Here are some examples:

## ST `<style>` tag with `lang="scss` vs VS Code

Sublime Text:

![Sublime Text SCSS Language](https://user-images.githubusercontent.com/575865/148598362-45039574-21d7-4671-a13a-d28d069ac431.png)

Here's the same thing in VS Code:

![VS Code SCSS Language](https://user-images.githubusercontent.com/575865/148598418-168671c1-4e05-4812-95b8-0e71ee8103b4.png)

## Script tag attributes

ST:

![Astro script tag with attributes](https://user-images.githubusercontent.com/575865/148598575-c2f89fb7-dde8-488c-aefb-d0788abd983c.png)

VS Code:
![VS Code script tag with attributes](https://user-images.githubusercontent.com/575865/148598751-1baed14d-48db-4605-b3a3-a53676fdc7ec.png)

And here's my Astro ST Package version:
![st-astro-package-version](https://user-images.githubusercontent.com/575865/148598821-aedffb7c-b1ca-4238-9096-0a7a335a57e1.png)

For reference I'm using the [Material Theme - Darker](https://github.com/equinusocio/material-theme) color scheme. But it looks like most/all of the default themes show the same behavior. 

Again, these are minor, bit I figured I would make a note of them. Thanks again for maintaining this package. 🌟

**Comment by Destiner** [comment]
Thanks, noting issues like this is appreciated!

In my last update, I had to diverge from the VSCode syntax rules because some regexes used there don't seem to work in ST. If you could split those into two separate items and submit as separate issues that would be great. I'd assume they would require separate fixes. I will try to look into them although can't guarantee the fix. So far I can tell that SCSS (and other CSS preprocessor formats)  syntax highlight in Astro relies on ST's internal library of highlights, so that integration is somehow not working it seems.
